import 'postgres.global'

import './-Postgres-createIndexes'
import './-Postgres-createTable'
import './-Postgres-getTableColumns'
import './-Postgres-getTableIndexes'
import './-Postgres-insert'
import './-Postgres-isTableExists'
import './-Postgres-select'
import './-Postgres-types'
import './-Postgres-useDatabase'
import './-Postgres-value'
