import 'defines/sky/standard'

import './define/global'

import './Array/global'
import './bind/global'
import './fetch/global'
import './Math/global'
import './measures/global'
import './Object/global'
import './Promise/global'
import './assert'
import './async'
import './canClone'
import './events'
import './extends_type'
import './hooks'
import './Map'
import './mixin'
import './not'
import './NullError'
import './onAsyncError'
import './repeat'
import './runtime'
import './singleton'
import './switch_thread'
import './transform'
