import '@sky-modules/cli/configuration'

export default {
    "name": "Sky Modules",
    "id": "sky",
    "scripts": {
        "cloudflare dev": "wrangler dev --remote"
    },
    "folders": {
        ".": "Sky",
        "cli": "Sky CLI",
        "pkgs": "Packages",
        "platform": "Sky ~ Platform",
        "universal": "Sky ~ Universal",
        "web": "Sky ~ Web",
        "core": "Sky ~ Core",
        "crypto": "Sky ~ Crypto",
        "database": "Sky ~ Database",
        "serverless": "Sky ~ Serverless",
        "utilities": "Sky ~ Utilities",
        "helpers": "Sky ~ Helpers",
        "modules": "Sky ~ Modules",
        "features": "Sky ~ Features",
        "effects": "Sky ~ Effects",
        "ecs": "Sky ~ ECS",
        "math": "Sky ~ Math",
        "design": "Sky ~ Design",
        "behavior": "Sky ~ Behavior",
        "Canvas": "Sky · Canvas",
        "Three": "Sky · Three",
        "vike": "Sky · Vike",
        "qwik": "Sky · Qwik",
        "solid": "Sky · Solid",
        "svelte": "Sky · Svelte",
        "vue": "Sky · Vue",
        "angular": "Sky · Angular",
        "react": "Sky · React",
        "playground": "Sky Playground",
        "../sky-modules-workspace-example": "Sky Playground  -  Workspace",
        "playground/Canvas": "Sky Playground  -  Canvas",
        "playground/Three": "Sky Playground  -  Three",
        "playground/node": "Sky Playground  -  Node",
        "playground/universal": "Sky Playground  -  Universal",
        "playground/qwik": "Sky Playground  -  Qwik",
        "playground/solid": "Sky Playground  -  Solid",
        "playground/svelte": "Sky Playground  -  Svelte",
        "playground/vue": "Sky Playground  -  Vue",
        "playground/angular": "Sky Playground  -  Angular",
        "playground/react": "Sky Playground  -  React",
        "playground/projects/game": "Sky Playground  -  Showcase Game"
    }
} satisfies Sky.WorkspaceConfig
