import 'mysql2.global'

import './-Mysql-createDatabase'
import './-Mysql-createTable'
import './-Mysql-getTableColumns'
import './-Mysql-getTableIndexes'
import './-Mysql-insert'
import './-Mysql-isTableExists'
import './-Mysql-select'
import './-Mysql-types'
import './-Mysql-useDatabase'
import './-Mysql-value'
