import Mysql from 'mysql2/promise'
export as namespace Mysql
export default Mysql
export {
    AuthPlugin,
    Connection,
    ConnectionConfig,
    ConnectionOptions,
    ErrorPacketParams,
    Field,
    FieldPacket,
    OkPacket,
    OkPacketParams,
    Pool,
    PoolCluster,
    PoolClusterOptions,
    PoolConnection,
    PoolOptions,
    Prepare,
    PrepareStatementInfo,
    PreparedStatementInfo,
    Query,
    QueryError,
    QueryOptions,
    ResultSetHeader,
    RowDataPacket,
    SslOptions,
    authPlugins,
    createConnection,
    createPool,
    createPoolCluster,
    createServer,
    escape,
    escapeId,
    format,
    raw,
} from 'mysql2/promise'
