import * as pkg from 'lottie-web'
import {
    AnimationConfig,
    AnimationConfigWithData,
    AnimationConfigWithPath,
    AnimationDirection,
    AnimationEventCallback,
    AnimationEventName,
    AnimationEvents,
    AnimationItem,
    AnimationSegment,
    BMCompleteEvent,
    BMCompleteLoopEvent,
    BMDestroyEvent,
    BMEnterFrameEvent,
    BMSegmentStartEvent,
    BaseRendererConfig,
    CanvasRendererConfig,
    FilterSizeConfig,
    HTMLRendererConfig,
    LottiePlayer,
    RendererType,
    SVGRendererConfig,
    TextDocumentData,
} from 'lottie-web'

export default pkg.default
export {
    AnimationConfig,
    AnimationConfigWithData,
    AnimationConfigWithPath,
    AnimationDirection,
    AnimationEventCallback,
    AnimationEventName,
    AnimationEvents,
    AnimationItem,
    AnimationSegment,
    BMCompleteEvent,
    BMCompleteLoopEvent,
    BMDestroyEvent,
    BMEnterFrameEvent,
    BMSegmentStartEvent,
    BaseRendererConfig,
    CanvasRendererConfig,
    FilterSizeConfig,
    HTMLRendererConfig,
    LottiePlayer,
    RendererType,
    SVGRendererConfig,
    TextDocumentData,
}
