import 'sky/core/global'
import 'sky/platform/web/initial'
import 'sky/helpers/global'
import 'sky/utilities/global'
import 'sky/features/asyncConstructor/global'
import 'sky/features/effect/global'
import 'sky/math/global'
import 'sky/Three/views/global'
import 'sky/Three/UI/global'

import 'pkgs/three/global'
