/**
 * Usage:
 *
 *  <button></button>
 *
 */
class Button extends HTMLElement {
  get _root() {
    return this.shadowRoot || this;
  }

  constructor() {
    super();
    const self = this;

    this.state = {
      isPressed: false,
      handleMouseDown() {
        self.state.isPressed = true;
        self.update();
      },
      handleMouseUp() {
        self.state.isPressed = false;
        self.update();
      },
    };
    if (!this.props) {
      this.props = {};
    }

    this.componentProps = [
      "disabled",
      "onClick",
      "loading",
      "children",
      "text",
    ];

    // used to keep track of all nodes created by show/for
    this.nodesToDestroy = [];
    // batch updates
    this.pendingUpdate = false;

    // Event handler for 'click' event on button-button-1
    this.onButtonButton1Click = (event) => {
      (this.props.disabled ? undefined : this.props.onClick)();
    };

    // Event handler for 'mousedown' event on button-button-1
    this.onButtonButton1Mousedown = (event) => {
      this.state.handleMouseDown();
    };

    // Event handler for 'mouseup' event on button-button-1
    this.onButtonButton1Mouseup = (event) => {
      this.state.handleMouseUp();
    };

    if (undefined) {
      this.attachShadow({ mode: "open" });
    }
  }

  destroyAnyNodes() {
    // destroy current view template refs before rendering again
    this.nodesToDestroy.forEach((el) => el.remove());
    this.nodesToDestroy = [];
  }

  connectedCallback() {
    this.getAttributeNames().forEach((attr) => {
      const jsVar = attr.replace(/-/g, "");
      const regexp = new RegExp(jsVar, "i");
      this.componentProps.forEach((prop) => {
        if (regexp.test(prop)) {
          const attrValue = this.getAttribute(attr);
          if (this.props[prop] !== attrValue) {
            this.props[prop] = attrValue;
          }
        }
      });
    });

    this._root.innerHTML = `
      <button data-el="button-button-1">
        <template data-el="show-button"><span>Loading...</span></template>
      </button>`;
    this.pendingUpdate = true;

    this.render();
    this.onMount();
    this.pendingUpdate = false;
    this.update();
  }

  showContent(el) {
    // https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement/content
    // grabs the content of a node that is between <template> tags
    // iterates through child nodes to register all content including text elements
    // attaches the content after the template

    const elementFragment = el.content.cloneNode(true);
    const children = Array.from(elementFragment.childNodes);
    children.forEach((child) => {
      if (el?.scope) {
        child.scope = el.scope;
      }
      if (el?.context) {
        child.context = el.context;
      }
      this.nodesToDestroy.push(child);
    });
    el.after(elementFragment);
  }

  onMount() {}

  onUpdate() {}

  update() {
    if (this.pendingUpdate === true) {
      return;
    }
    this.pendingUpdate = true;
    this.render();
    this.onUpdate();
    this.pendingUpdate = false;
  }

  render() {
    // re-rendering needs to ensure that all nodes generated by for/show are refreshed
    this.destroyAnyNodes();
    this.updateBindings();
  }

  updateBindings() {
    this._root.querySelectorAll("[data-el='button-button-1']").forEach((el) => {
      Object.assign(el.style, getButtonStyle());
      el.removeEventListener("click", this.onButtonButton1Click);
      el.addEventListener("click", this.onButtonButton1Click);
      el.removeEventListener("mousedown", this.onButtonButton1Mousedown);
      el.addEventListener("mousedown", this.onButtonButton1Mousedown);
      el.removeEventListener("mouseup", this.onButtonButton1Mouseup);
      el.addEventListener("mouseup", this.onButtonButton1Mouseup);
      el.setAttribute("disabled", this.props.disabled);
    });

    this._root.querySelectorAll("[data-el='show-button']").forEach((el) => {
      const whenCondition = this.props.loading;
      if (whenCondition) {
        this.showContent(el);
      }
    });
  }

  // Helper to render content
  renderTextNode(el, text) {
    const textNode = document.createTextNode(text);
    if (el?.scope) {
      textNode.scope = el.scope;
    }
    if (el?.context) {
      textNode.context = el.context;
    }
    el.after(textNode);
    this.nodesToDestroy.push(el.nextSibling);
  }
}

customElements.define("button", Button);
