/**
 * Usage:
 *
 *  <foo></foo>
 *
 */
class Foo extends HTMLElement {
  get _root() {
    return this.shadowRoot || this;
  }

  constructor() {
    super();
    const self = this;

    this.state = {
      count: self.props.foo || 0,
      increment() {
        self.state.count++;
      },
    };
    if (!this.props) {
      this.props = {};
    }

    this.componentProps = ["foo", "onClick", "className"];

    // used to keep track of all nodes created by show/for
    this.nodesToDestroy = [];
    // batch updates
    this.pendingUpdate = false;

    // Event handler for 'click' event on div-foo-1
    this.onDivFoo1Click = (event) => {
      this.state.increment();
      this.props.onClick?.();
    };

    // Event handler for 'click' event on button-foo-1
    this.onButtonFoo1Click = (event) => {
      this.state.increment();
    };

    if (undefined) {
      this.attachShadow({ mode: "open" });
    }
  }

  destroyAnyNodes() {
    // destroy current view template refs before rendering again
    this.nodesToDestroy.forEach((el) => el.remove());
    this.nodesToDestroy = [];
  }

  connectedCallback() {
    this.getAttributeNames().forEach((attr) => {
      const jsVar = attr.replace(/-/g, "");
      const regexp = new RegExp(jsVar, "i");
      this.componentProps.forEach((prop) => {
        if (regexp.test(prop)) {
          const attrValue = this.getAttribute(attr);
          if (this.props[prop] !== attrValue) {
            this.props[prop] = attrValue;
          }
        }
      });
    });

    this._root.innerHTML = `
      <div data-el="div-foo-1">
        <h3>Universal Foo Component</h3>
        <p>
          Initial value:
          <template data-el="div-foo-2"><!-- props.foo --></template>
        </p>
        <p>
          Current count:
          <template data-el="div-foo-3"><!-- state.count --></template>
        </p>
        <button data-el="button-foo-1">Increment</button>
      </div>`;
    this.pendingUpdate = true;

    this.render();
    this.onMount();
    this.pendingUpdate = false;
    this.update();
  }

  onMount() {}

  onUpdate() {}

  update() {
    if (this.pendingUpdate === true) {
      return;
    }
    this.pendingUpdate = true;
    this.render();
    this.onUpdate();
    this.pendingUpdate = false;
  }

  render() {
    // re-rendering needs to ensure that all nodes generated by for/show are refreshed
    this.destroyAnyNodes();
    this.updateBindings();
  }

  updateBindings() {
    this._root.querySelectorAll("[data-el='div-foo-1']").forEach((el) => {
      el.removeEventListener("click", this.onDivFoo1Click);
      el.addEventListener("click", this.onDivFoo1Click);
      Object.assign(el.style, {
        padding: "16px",
        border: "1px solid #ccc",
        borderRadius: "8px",
        cursor: "pointer",
        backgroundColor: "#f9f9f9",
      });
      el.className = this.props.className;
    });

    this._root.querySelectorAll("[data-el='div-foo-2']").forEach((el) => {
      this.renderTextNode(el, this.props.foo);
    });

    this._root.querySelectorAll("[data-el='div-foo-3']").forEach((el) => {
      this.renderTextNode(el, this.state.count);
    });

    this._root.querySelectorAll("[data-el='button-foo-1']").forEach((el) => {
      el.removeEventListener("click", this.onButtonFoo1Click);
      el.addEventListener("click", this.onButtonFoo1Click);
    });
  }

  // Helper to render content
  renderTextNode(el, text) {
    const textNode = document.createTextNode(text);
    if (el?.scope) {
      textNode.scope = el.scope;
    }
    if (el?.context) {
      textNode.context = el.context;
    }
    el.after(textNode);
    this.nodesToDestroy.push(el.nextSibling);
  }
}

customElements.define("foo", Foo);
