// Auto-generated global imports for @sky-modules/core
// Generated from slice.json modules

import './Callback/global'
import './Class/global'
import './Console/global'
import './EventEmitter/global'
import './Math/global'
import './Object/global'
import './PromisePool/global'
import './as/global'
import './assert/global'
import './async-creation/global'
import './async/global'
import './bind/global'
import './canClone/global'
import './deferred/global'
import './define/global'
import './events/global'
import './fetch/global'
import './globalify/global'
import './hmr/global'
import './hooks/global'
import './idle/global'
import './justTry/global'
import './measures/defineMeasures/global'
import './measures/global'
import './mergeNamespace/global'
import './mixin/global'
import './mode/global'
import './not/global'
import './repeat/global'
import './runtime/global'
import './switch_thread/global'
import './transform/global'
import './type-guards/global'
