export { default } from './Canvas'
export * from './Canvas'

// import './_Canvas.drawRoundedRect'
// import './_Canvas.Sprite'
// import './_Canvas.utilities'
// import './_Canvas+drawHexagon'
// import './_Canvas+drawImage'
// import './_Canvas+drawText'
// import './_Canvas+measureText'
