// 🔄 Default Reset Brand Configuration
import foundation from './reset.brand-foundation'

import type { BrandDescription } from '@sky-modules/design/Brand'
import type Brand from '@sky-modules/design/Brand'

// Clean, minimal brand with neutral colors and standard spacing
const resetBrand = {
    foundation,
    semantic: {
        spacing: {
            none: '0',
            xs: '0.25rem',
            sm: '0.5rem',
            md: '1rem',
            lg: '1.5rem',
            xl: '2rem',
            '2xl': '3rem',
            '3xl': '4rem',
            '4xl': '5rem',
            '5xl': '6rem',
            '6xl': '8rem',
        },
        sizing: {
            xs: '1rem',
            sm: '1.5rem',
            md: '2rem',
            lg: '2.5rem',
            xl: '3rem',
            '2xl': '4rem',
            '3xl': '5rem',
            '4xl': '6rem',
            '5xl': '8rem',
            '6xl': '10rem',
            full: '100%',
            screen: '100vh',
        },
        colors: {
            background: {
                primary: '#fff',
                secondary: '#f4f4f5',
                tertiary: '#e4e4e7',
                inverse: '#09090b',
                backdrop: 'rgb(0 0 0 / 50%)',
                overlay: 'rgb(0 0 0 / 80%)',
                scrim: 'rgb(0 0 0 / 25%)',
            },
            foreground: {
                primary: '#09090b',
                secondary: '#27272a',
                tertiary: '#71717a',
                inverse: '#fff',
                disabled: '#a1a1aa',
                placeholder: '#71717a',
            },
            border: {
                primary: '#e4e4e7',
                secondary: '#f4f4f5',
                tertiary: '#fafafa',
                inverse: '#27272a',
                focus: '#0ea5e9',
                error: '#ef4444',
                warning: '#f59e0b',
                success: '#22c55e',
                info: '#06b6d4',
            },
            brand: {
                primary: '#0ea5e9',
                primaryHover: '#0284c7',
                primaryActive: '#0369a1',
                primarySubtle: 'rgb(14 165 233 / 10%)',
                secondary: '#38bdf8',
                secondaryHover: '#0ea5e9',
                secondaryActive: '#0284c7',
                secondarySubtle: 'rgb(56 189 248 / 10%)',
            },
            status: {
                success: '#22c55e',
                successHover: '#16a34a',
                successActive: '#15803d',
                successSubtle: 'rgb(34 197 94 / 10%)',
                error: '#ef4444',
                errorHover: '#dc2626',
                errorActive: '#b91c1c',
                errorSubtle: 'rgb(239 68 68 / 10%)',
                warning: '#f59e0b',
                warningHover: '#d97706',
                warningActive: '#b45309',
                warningSubtle: 'rgb(245 158 11 / 10%)',
                info: '#06b6d4',
                infoHover: '#0891b2',
                infoActive: '#0e7490',
                infoSubtle: 'rgb(6 182 212 / 10%)',
            },
            surface: {
                raised: '#fff',
                overlay: 'rgb(255 255 255 / 95%)',
                sunken: '#f4f4f5',
                selected: 'rgb(14 165 233 / 10%)',
                disabled: 'rgb(161 161 170 / 50%)',
            },
            effects: {
                glowFocus: '0 0 8px rgb(14 165 233 / 40%)',
                glowHover: '0 0 4px rgb(14 165 233 / 50%)',
                glowActive: '0 0 12px rgb(14 165 233 / 35%)',
                glowSubtle: '0 0 2px rgb(14 165 233 / 60%)',
                glowStrong: '0 0 16px rgb(14 165 233 / 30%)',
                glowBrand: '0 0 8px rgb(14 165 233 / 40%)',
                glowSuccess: '0 0 8px rgb(34 197 94 / 35%)',
                glowError: '0 0 8px rgb(239 68 68 / 35%)',
                glowWarning: '0 0 8px rgb(245 158 11 / 35%)',
                glowInfo: '0 0 8px rgb(6 182 212 / 35%)',
            },
        },
        typography: {
            display: {
                large: '4.5rem',
                medium: '3.75rem',
                small: '3rem',
            },
            headline: {
                large: '2.25rem',
                medium: '1.875rem',
                small: '1.5rem',
            },
            title: {
                large: '1.25rem',
                medium: '1.125rem',
                small: '1rem',
            },
            label: {
                large: '0.875rem',
                medium: '0.75rem',
                small: '0.675rem',
            },
            body: {
                large: '1rem',
                medium: '0.875rem',
                small: '0.75rem',
            },
        },
    },
    global: {
        mode: 'light',
        accessibility: {
            reducedMotion: false,
            highContrast: false,
            focusRing: {
                width: '2px',
                style: 'solid',
                color: '#0ea5e9',
                offset: '2px',
            },
        },
        i18n: {
            direction: 'ltr',
            locale: 'en-US',
            timezone: 'UTC',
            currency: 'USD',
            numberFormat: {
                decimal: '.',
                thousands: ',',
            },
            dateFormat: {
                short: 'MM/dd/yyyy',
                medium: 'MMM dd, yyyy',
                long: 'MMMM dd, yyyy',
                full: 'EEEE, MMMM dd, yyyy',
            },
        },
        content: {
            tone: 'professional',
            voice: 'active',
            microcopy: {
                loading: 'Loading...',
                empty: 'No data available',
                error: 'Something went wrong',
                success: 'Success!',
                retry: 'Try again',
                cancel: 'Cancel',
                confirm: 'Confirm',
                save: 'Save',
                delete: 'Delete',
                edit: 'Edit',
                create: 'Create',
                update: 'Update',
                search: 'Search',
                filter: 'Filter',
                sort: 'Sort',
                more: 'More',
                less: 'Less',
                previous: 'Previous',
                next: 'Next',
                close: 'Close',
                open: 'Open',
            },
        },
    },
    components: {} as Brand['components'],
    charts: {} as Brand['charts'],
    animations: {} as Brand['animations'],
    layout: {} as Brand['layout'],
} satisfies BrandDescription
export default resetBrand
