/* eslint-disable @typescript-eslint/no-explicit-any */
// 🎨 Sky Brand Configuration
import type { BrandDescription } from '@sky-modules/design/Brand'

// Sky theme
export default {
    name: 'sky',
    foundation: {
        colors: {
            brand: {
                50: '#f0fdfa',
                100: '#ccfbf1',
                200: '#99f6e4',
                300: '#5eead4',
                400: '#2dd4bf',
                500: '#14b8a6',
                600: '#0d9488',
                700: '#0f766e',
                800: '#115e59',
                900: '#134e4a',
                950: '#042f2e',
            },
        },
    },
    semantic: {
        colors: {
            background: {
                primary: '#0a0a0a',
                secondary: '#121212',
                tertiary: '#1c1c1c',
                inverse: '#fafafa',
                backdrop: 'rgb(10 10 10 / 80%)',
                overlay: 'rgb(10 10 10 / 95%)',
                scrim: 'rgb(0 0 0 / 50%)',
            },
            foreground: {
                primary: '#fafafa',
                secondary: '#d4d4d8',
                tertiary: '#a1a1aa',
                inverse: '#0a0a0a',
                disabled: '#71717a',
                placeholder: '#52525b',
            },
            border: {
                primary: 'rgb(255 255 255 / 10%)',
                secondary: 'rgb(255 255 255 / 5%)',
                tertiary: 'rgb(255 255 255 / 2%)',
                inverse: 'rgb(0 0 0 / 10%)',
                focus: '#22d3ee',
                error: '#ef4444',
                warning: '#f59e0b',
                success: '#22d3ee',
                info: '#22d3ee',
            },
            brand: {
                primary: '#22d3ee',
                primaryHover: '#06b6d4',
                primaryActive: '#0891b2',
                primarySubtle: 'rgb(34 211 238 / 10%)',
                secondary: '#e879f9',
                secondaryHover: '#d946ef',
                secondaryActive: '#c026d3',
                secondarySubtle: 'rgb(232 121 249 / 10%)',
            },
            status: {
                success: '#34d399',
                successHover: '#10b981',
                successActive: '#059669',
                successSubtle: '#34d399 / 10%',
                error: '#ef4444',
                errorHover: '#dc2626',
                errorActive: '#b91c1c',
                errorSubtle: '#ef4444 / 10%',
                warning: '#f59e0b',
                warningHover: '#d97706',
                warningActive: '#b45309',
                warningSubtle: '#f59e0b / 10%',
                info: '#22d3ee',
                infoHover: '#06b6d4',
                infoActive: '#0891b2',
                infoSubtle: '#22d3ee / 10%',
            },
            surface: {
                raised: '#303030',
                overlay: 'rgb(48 48 48 / 90%)',
                sunken: '#121212',
                selected: 'rgb(34 211 238 / 10%)',
                disabled: 'rgb(113 113 122 / 50%)',
            },
            effects: {
                // Primary/Secondary/Tertiary hierarchy - logo colors
                glowPrimary: '0 0 12px #22d3ee / 40%', // Cyan
                glowSecondary: '0 0 12px #e879f9 / 40%', // Pink/Fuchsia
                glowTertiary: '0 0 12px #34d399 / 40%', // Green

                // Interactive states
                glowFocus: '0 0 8px #22d3ee / 50%',
                glowHover: '0 0 6px #22d3ee / 60%',
                glowActive: '0 0 14px #22d3ee / 35%',
                glowSubtle: '0 0 4px #22d3ee / 70%',
                glowStrong: '0 0 20px #22d3ee / 30%',

                // Contextual glows - using logo colors
                glowBrand: '0 0 10px #22d3ee / 45%', // Cyan
                glowSuccess: '0 0 8px #34d399 / 40%', // Green
                glowError: '0 0 8px #ef4444 / 40%', // Red
                glowWarning: '0 0 8px #f59e0b / 40%', // Amber
                glowInfo: '0 0 8px #e879f9 / 40%', // Pink/Fuchsia
            },
        },
        opacity: {
            disabled: '0.4',
            subtle: '0.6',
            medium: '0.8',
            visible: '1',
            hidden: '0',
            overlay: '0.95',
            backdrop: '0.80',
        },
        duration: {
            instant: '0ms',
            fast: '120ms',
            normal: '200ms',
            slow: '300ms',
            slower: '500ms',
        },
        zIndex: {
            dropdown: 1000,
            sticky: 1020,
            fixed: 1030,
            modal: 1040,
            popover: 1050,
            tooltip: 1060,
            toast: 1070,
            overlay: 1080,
        },
        glow: {
            xs: '0 0 2px rgb(34 211 238 / 70%)',
            sm: '0 0 4px rgb(34 211 238 / 60%)',
            base: '0 0 8px rgb(34 211 238 / 50%)',
            md: '0 0 12px rgb(34 211 238 / 40%)',
            lg: '0 0 16px rgb(34 211 238 / 35%)',
            xl: '0 0 24px rgb(34 211 238 / 30%)',
            '2xl': '0 0 32px rgb(34 211 238 / 25%)',
            '3xl': '0 0 48px rgb(34 211 238 / 20%)',
            none: 'none',
        },
        animations: {
            primaryIn: 'cubic-bezier(0.4, 0, 1, 1)',
            primaryOut: 'cubic-bezier(0, 0, 0.2, 1)',
            primaryInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
            secondaryIn: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
            secondaryOut: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
            secondaryInOut: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
            tertiaryIn: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
            tertiaryOut: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
            tertiaryInOut: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        },
        typography: {
            display: {
                large: '4.5rem',
                medium: '3.75rem',
                small: '3rem',
            },
            headline: {
                large: '2.25rem',
                medium: '1.875rem',
                small: '1.5rem',
            },
            title: {
                large: '1.25rem',
                medium: '1.125rem',
                small: '1rem',
            },
            label: {
                large: '0.875rem',
                medium: '0.75rem',
                small: '0.675rem',
            },
            body: {
                large: '1rem',
                medium: '0.875rem',
                small: '0.75rem',
            },
        },
    },
    global: {
        theme: 'dark',
        accessibility: {
            reducedMotion: false,
            highContrast: false,
            focusRing: {
                width: '2px',
                style: 'solid',
                color: '#22d3ee',
                offset: '2px',
            },
        },
        i18n: {
            direction: 'ltr',
            locale: 'en-US',
            timezone: 'UTC',
            currency: 'USD',
            numberFormat: {
                decimal: '.',
                thousands: ',',
            },
            dateFormat: {
                short: 'MM/dd/yyyy',
                medium: 'MMM dd, yyyy',
                long: 'MMMM dd, yyyy',
                full: 'EEEE, MMMM dd, yyyy',
            },
        },
        content: {
            tone: 'professional',
            voice: 'active',
            microcopy: {
                loading: 'Loading...',
                empty: 'No data available',
                error: 'Something went wrong',
                success: 'Success!',
                retry: 'Try again',
                cancel: 'Cancel',
                confirm: 'Confirm',
                save: 'Save',
                delete: 'Delete',
                edit: 'Edit',
                create: 'Create',
                update: 'Update',
                search: 'Search',
                filter: 'Filter',
                sort: 'Sort',
                more: 'More',
                less: 'Less',
                previous: 'Previous',
                next: 'Next',
                close: 'Close',
                open: 'Open',
            },
        },
    },
    themes: {
        mode: 'palette',
        defaultMode: 'dark',
        palettes: {
            light: {
                surface: {
                    primary: '#ffffff',
                    secondary: '#f8f9fa',
                    tertiary: '#e9ecef',
                    inverse: '#0a0a0a',
                    backdrop: 'rgb(255 255 255 / 80%)',
                    overlay: 'rgb(255 255 255 / 95%)',
                    raised: '#f1f3f4',
                    sunken: '#f8f9fa',
                    selected: 'rgb(34 211 238 / 10%)',
                    disabled: 'rgb(158 158 158 / 50%)',
                },
                content: {
                    primary: '#0a0a0a',
                    secondary: '#374151',
                    tertiary: '#6b7280',
                    inverse: '#ffffff',
                    disabled: '#9ca3af',
                    placeholder: '#d1d5db',
                    onBrand: '#ffffff',
                },
                border: {
                    primary: 'rgb(0 0 0 / 10%)',
                    secondary: 'rgb(0 0 0 / 5%)',
                    tertiary: 'rgb(0 0 0 / 2%)',
                    inverse: 'rgb(255 255 255 / 10%)',
                    focus: '#22d3ee',
                    disabled: 'rgb(0 0 0 / 5%)',
                },
                brand: {
                    primary: '#22d3ee',
                    primaryHover: '#06b6d4',
                    primaryActive: '#0891b2',
                    primarySubtle: 'rgb(34 211 238 / 10%)',
                    secondary: '#e879f9',
                    secondaryHover: '#d946ef',
                    secondaryActive: '#c026d3',
                    secondarySubtle: 'rgb(232 121 249 / 10%)',
                },
                status: {
                    success: '#059669',
                    successHover: '#047857',
                    successSubtle: 'rgb(5 150 105 / 10%)',
                    error: '#dc2626',
                    errorHover: '#b91c1c',
                    errorSubtle: 'rgb(220 38 38 / 10%)',
                    warning: '#d97706',
                    warningHover: '#b45309',
                    warningSubtle: 'rgb(217 119 6 / 10%)',
                    info: '#0891b2',
                    infoHover: '#0e7490',
                    infoSubtle: 'rgb(8 145 178 / 10%)',
                },
                interactive: {
                    idle: 'rgb(0 0 0 / 5%)',
                    hover: 'rgb(0 0 0 / 8%)',
                    active: 'rgb(0 0 0 / 12%)',
                    focus: '#22d3ee',
                    disabled: 'rgb(0 0 0 / 3%)',
                    selected: 'rgb(34 211 238 / 15%)',
                    pressed: 'rgb(0 0 0 / 15%)',
                },
            },
            dark: {
                surface: {
                    primary: '#0a0a0a',
                    secondary: '#121212',
                    tertiary: '#1c1c1c',
                    inverse: '#fafafa',
                    backdrop: 'rgb(10 10 10 / 80%)',
                    overlay: 'rgb(10 10 10 / 95%)',
                    raised: '#303030',
                    sunken: '#121212',
                    selected: 'rgb(34 211 238 / 10%)',
                    disabled: 'rgb(113 113 122 / 50%)',
                },
                content: {
                    primary: '#fafafa',
                    secondary: '#d4d4d8',
                    tertiary: '#a1a1aa',
                    inverse: '#0a0a0a',
                    disabled: '#71717a',
                    placeholder: '#52525b',
                    onBrand: '#0a0a0a',
                },
                border: {
                    primary: 'rgb(255 255 255 / 10%)',
                    secondary: 'rgb(255 255 255 / 5%)',
                    tertiary: 'rgb(255 255 255 / 2%)',
                    inverse: 'rgb(0 0 0 / 10%)',
                    focus: '#22d3ee',
                    disabled: 'rgb(255 255 255 / 5%)',
                },
                brand: {
                    primary: '#22d3ee',
                    primaryHover: '#06b6d4',
                    primaryActive: '#0891b2',
                    primarySubtle: 'rgb(34 211 238 / 10%)',
                    secondary: '#e879f9',
                    secondaryHover: '#d946ef',
                    secondaryActive: '#c026d3',
                    secondarySubtle: 'rgb(232 121 249 / 10%)',
                },
                status: {
                    success: '#34d399',
                    successHover: '#10b981',
                    successSubtle: 'rgb(52 211 153 / 10%)',
                    error: '#ef4444',
                    errorHover: '#dc2626',
                    errorSubtle: 'rgb(239 68 68 / 10%)',
                    warning: '#f59e0b',
                    warningHover: '#d97706',
                    warningSubtle: 'rgb(245 158 11 / 10%)',
                    info: '#22d3ee',
                    infoHover: '#06b6d4',
                    infoSubtle: 'rgb(34 211 238 / 10%)',
                },
                interactive: {
                    idle: 'rgb(255 255 255 / 10%)',
                    hover: 'rgb(255 255 255 / 15%)',
                    active: 'rgb(255 255 255 / 20%)',
                    focus: '#22d3ee',
                    disabled: 'rgb(255 255 255 / 5%)',
                    selected: 'rgb(34 211 238 / 15%)',
                    pressed: 'rgb(255 255 255 / 25%)',
                },
            },
            pink: {
                surface: {
                    primary: '#0f0a0d',
                    secondary: '#1a0d15',
                    tertiary: '#2d1522',
                    inverse: '#fdf2f8',
                    backdrop: 'rgb(15 10 13 / 80%)',
                    overlay: 'rgb(15 10 13 / 95%)',
                    raised: '#3f1d2e',
                    sunken: '#1a0d15',
                    selected: 'rgb(236 72 153 / 10%)',
                    disabled: 'rgb(133 77 102 / 50%)',
                },
                content: {
                    primary: '#fdf2f8',
                    secondary: '#f3e8ff',
                    tertiary: '#ddd6fe',
                    inverse: '#0f0a0d',
                    disabled: '#9f7aea',
                    placeholder: '#7c3aed',
                    onBrand: '#fdf2f8',
                },
                border: {
                    primary: 'rgb(236 72 153 / 15%)',
                    secondary: 'rgb(236 72 153 / 8%)',
                    tertiary: 'rgb(236 72 153 / 4%)',
                    inverse: 'rgb(15 10 13 / 15%)',
                    focus: '#ec4899',
                    disabled: 'rgb(236 72 153 / 8%)',
                },
                brand: {
                    primary: '#ec4899',
                    primaryHover: '#db2777',
                    primaryActive: '#be185d',
                    primarySubtle: 'rgb(236 72 153 / 10%)',
                    secondary: '#d946ef',
                    secondaryHover: '#c026d3',
                    secondaryActive: '#a21caf',
                    secondarySubtle: 'rgb(217 70 239 / 10%)',
                },
                status: {
                    success: '#10b981',
                    successHover: '#059669',
                    successSubtle: 'rgb(16 185 129 / 10%)',
                    error: '#ef4444',
                    errorHover: '#dc2626',
                    errorSubtle: 'rgb(239 68 68 / 10%)',
                    warning: '#f59e0b',
                    warningHover: '#d97706',
                    warningSubtle: 'rgb(245 158 11 / 10%)',
                    info: '#ec4899',
                    infoHover: '#db2777',
                    infoSubtle: 'rgb(236 72 153 / 10%)',
                },
                interactive: {
                    idle: 'rgb(236 72 153 / 12%)',
                    hover: 'rgb(236 72 153 / 18%)',
                    active: 'rgb(236 72 153 / 25%)',
                    focus: '#ec4899',
                    disabled: 'rgb(236 72 153 / 8%)',
                    selected: 'rgb(236 72 153 / 20%)',
                    pressed: 'rgb(236 72 153 / 30%)',
                },
            },
        },
    },
    components: {
        prose: {
            // Base prose styles
            maxWidth: '65ch',
            color: 'rgb(212 212 216)',
            fontSize: '1rem',
            lineHeight: '1.75',
            fontFamily: 'ui-sans-serif, system-ui, sans-serif',

            // Headings
            h1: {
                color: 'rgb(250 250 250)',
                fontSize: '2.25rem',
                fontWeight: '800',
                lineHeight: '1.1111111',
                marginTop: '0',
                marginBottom: '0.8888889em',
            },
            h2: {
                color: 'rgb(250 250 250)',
                fontSize: '1.5rem',
                fontWeight: '700',
                lineHeight: '1.3333333',
                marginTop: '2em',
                marginBottom: '1em',
            },
            h3: {
                color: 'rgb(250 250 250)',
                fontSize: '1.25rem',
                fontWeight: '600',
                lineHeight: '1.6',
                marginTop: '1.6em',
                marginBottom: '0.6em',
            },
            h4: {
                color: 'rgb(250 250 250)',
                fontSize: '1rem',
                fontWeight: '600',
                lineHeight: '1.5',
                marginTop: '1.5em',
                marginBottom: '0.5em',
            },
            h5: {
                color: 'rgb(250 250 250)',
                fontSize: '0.875rem',
                fontWeight: '600',
                lineHeight: '1.5714286',
                marginTop: '1.5714286em',
                marginBottom: '0.5714286em',
            },
            h6: {
                color: 'rgb(250 250 250)',
                fontSize: '0.875rem',
                fontWeight: '600',
                lineHeight: '1.5714286',
                marginTop: '1.5714286em',
                marginBottom: '0.5714286em',
            },

            // Text elements
            p: {
                marginTop: '1.25em',
                marginBottom: '1.25em',
            },
            lead: {
                color: 'rgb(161 161 170)',
                fontSize: '1.25rem',
                lineHeight: '1.6',
                marginTop: '1.2em',
                marginBottom: '1.2em',
            },
            strong: {
                color: 'rgb(250 250 250)',
                fontWeight: '600',
            },
            em: {
                color: 'inherit',
                fontStyle: 'italic',
            },

            // Links
            a: {
                color: '#22d3ee',
                textDecoration: 'underline',
                fontWeight: '500',
            },
            'a:hover': {
                color: '#06b6d4',
                textDecoration: 'none',
            },

            // Lists
            ul: {
                listStyleType: 'disc',
                marginTop: '1.25em',
                marginBottom: '1.25em',
                paddingLeft: '1.625em',
            },
            ol: {
                listStyleType: 'decimal',
                marginTop: '1.25em',
                marginBottom: '1.25em',
                paddingLeft: '1.625em',
            },
            li: {
                marginTop: '0.5em',
                marginBottom: '0.5em',
            },

            // Code
            code: {
                color: 'rgb(250 250 250)',
                backgroundColor: 'rgb(39 39 42)',
                fontFamily:
                    'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
                fontSize: '0.875em',
                fontWeight: '600',
                padding: '0.2em 0.4em',
                borderRadius: '0.375rem',
            },
            pre: {
                color: 'rgb(250 250 250)',
                backgroundColor: 'rgb(39 39 42)',
                fontFamily:
                    'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
                fontSize: '0.875em',
                lineHeight: '1.7142857',
                marginTop: '1.7142857em',
                marginBottom: '1.7142857em',
                padding: '0.8571429em 1.1428571em',
                borderRadius: '0.375rem',
                overflowX: 'auto',
            },
            'pre code': {
                backgroundColor: 'transparent',
                color: 'inherit',
                fontSize: 'inherit',
                fontWeight: '400',
                padding: '0',
            },

            // Blockquotes
            blockquote: {
                fontWeight: '500',
                fontStyle: 'italic',
                color: 'rgb(161 161 170)',
                borderLeft: '0.25rem solid rgb(63 63 70)',
                borderColor: 'rgb(63 63 70)',
                quotes: '"\\201C""\\201D""\\2018""\\2019"',
                marginTop: '1.6em',
                marginBottom: '1.6em',
                paddingLeft: '1em',
            },
            'blockquote p:first-of-type::before': {
                content: 'open-quote',
            },
            'blockquote p:last-of-type::after': {
                content: 'close-quote',
            },

            // Tables
            table: {
                width: '100%',
                tableLayout: 'auto',
                textAlign: 'left',
                marginTop: '2em',
                marginBottom: '2em',
                fontSize: '0.875em',
                lineHeight: '1.7142857',
            },
            thead: {
                borderBottomWidth: '1px',
                borderBottomColor: 'rgb(63 63 70)',
            },
            'thead th': {
                color: 'rgb(250 250 250)',
                fontWeight: '600',
                verticalAlign: 'bottom',
                paddingRight: '0.5714286em',
                paddingBottom: '0.5714286em',
                paddingLeft: '0.5714286em',
            },
            'tbody tr': {
                borderBottomWidth: '1px',
                borderBottomColor: 'rgb(39 39 42)',
            },
            'tbody td': {
                verticalAlign: 'baseline',
                paddingTop: '0.5714286em',
                paddingRight: '0.5714286em',
                paddingBottom: '0.5714286em',
                paddingLeft: '0.5714286em',
            },

            // Images & Media
            img: {
                marginTop: '2em',
                marginBottom: '2em',
            },
            video: {
                marginTop: '2em',
                marginBottom: '2em',
            },
            figure: {
                marginTop: '2em',
                marginBottom: '2em',
            },
            'figure > *': {
                marginTop: '0',
                marginBottom: '0',
            },
            figcaption: {
                color: 'rgb(161 161 170)',
                fontSize: '0.875em',
                lineHeight: '1.4285714',
                marginTop: '0.8571429em',
            },

            // Horizontal rules
            hr: {
                borderColor: 'rgb(39 39 42)',
                borderTopWidth: '1px',
                marginTop: '3em',
                marginBottom: '3em',
            },

            // Size variants
            sm: {
                fontSize: '0.875rem',
                lineHeight: '1.7142857',
                p: { marginTop: '1.1428571em', marginBottom: '1.1428571em' },
                h1: {
                    fontSize: '2.1428571em',
                    marginTop: '0',
                    marginBottom: '0.8em',
                    lineHeight: '1.2',
                },
                h2: {
                    fontSize: '1.4285714em',
                    marginTop: '1.6em',
                    marginBottom: '0.8em',
                    lineHeight: '1.4',
                },
                h3: {
                    fontSize: '1.2857143em',
                    marginTop: '1.5555556em',
                    marginBottom: '0.4444444em',
                    lineHeight: '1.5555556',
                },
                h4: {
                    fontSize: '1.1428571em',
                    marginTop: '1.25em',
                    marginBottom: '0.5em',
                    lineHeight: '1.5',
                },
                h5: {
                    fontSize: '1em',
                    marginTop: '1.4285714em',
                    marginBottom: '0.5714286em',
                    lineHeight: '1.5714286',
                },
                h6: {
                    fontSize: '1em',
                    marginTop: '1.4285714em',
                    marginBottom: '0.5714286em',
                    lineHeight: '1.5714286',
                },
                code: { fontSize: '0.8571429em' },
                pre: {
                    fontSize: '0.8571429em',
                    lineHeight: '1.6666667',
                    marginTop: '1.6666667em',
                    marginBottom: '1.6666667em',
                    borderRadius: '0.25rem',
                    padding: '0.6666667em 1em',
                },
            },
            lg: {
                fontSize: '1.125rem',
                lineHeight: '1.7777778',
                p: { marginTop: '1.3333333em', marginBottom: '1.3333333em' },
                h1: {
                    fontSize: '2.6666667em',
                    marginTop: '0',
                    marginBottom: '0.8333333em',
                    lineHeight: '1',
                },
                h2: {
                    fontSize: '1.6666667em',
                    marginTop: '1.8666667em',
                    marginBottom: '1.0666667em',
                    lineHeight: '1.3333333',
                },
                h3: {
                    fontSize: '1.3333333em',
                    marginTop: '1.6666667em',
                    marginBottom: '0.6666667em',
                    lineHeight: '1.5',
                },
                h4: {
                    fontSize: '1.1111111em',
                    marginTop: '1.5em',
                    marginBottom: '0.5em',
                    lineHeight: '1.5',
                },
                h5: {
                    fontSize: '1em',
                    marginTop: '1.7777778em',
                    marginBottom: '0.4444444em',
                    lineHeight: '1.5555556',
                },
                h6: {
                    fontSize: '1em',
                    marginTop: '1.7777778em',
                    marginBottom: '0.4444444em',
                    lineHeight: '1.5555556',
                },
                code: { fontSize: '0.8888889em' },
                pre: {
                    fontSize: '0.8888889em',
                    lineHeight: '1.75',
                    marginTop: '2em',
                    marginBottom: '2em',
                    borderRadius: '0.375rem',
                    padding: '1em 1.5em',
                },
            },
            xl: {
                fontSize: '1.25rem',
                lineHeight: '1.8',
                p: { marginTop: '1.2em', marginBottom: '1.2em' },
                h1: {
                    fontSize: '2.8em',
                    marginTop: '0',
                    marginBottom: '0.8571429em',
                    lineHeight: '1',
                },
                h2: {
                    fontSize: '1.8em',
                    marginTop: '1.5555556em',
                    marginBottom: '0.8888889em',
                    lineHeight: '1.1111111',
                },
                h3: {
                    fontSize: '1.5em',
                    marginTop: '1.6em',
                    marginBottom: '0.6666667em',
                    lineHeight: '1.3333333',
                },
                h4: {
                    fontSize: '1.25em',
                    marginTop: '1.5em',
                    marginBottom: '0.5em',
                    lineHeight: '1.5',
                },
                h5: {
                    fontSize: '1.1em',
                    marginTop: '1.8181818em',
                    marginBottom: '0.4545455em',
                    lineHeight: '1.4545455',
                },
                h6: {
                    fontSize: '1.1em',
                    marginTop: '1.8181818em',
                    marginBottom: '0.4545455em',
                    lineHeight: '1.4545455',
                },
                code: { fontSize: '0.9em' },
                pre: {
                    fontSize: '0.9em',
                    lineHeight: '1.7777778',
                    marginTop: '2em',
                    marginBottom: '2em',
                    borderRadius: '0.5rem',
                    padding: '1.1111111em 1.3333333em',
                },
            },
            '2xl': {
                fontSize: '1.5rem',
                lineHeight: '1.6666667',
                p: { marginTop: '1.3333333em', marginBottom: '1.3333333em' },
                h1: {
                    fontSize: '2.6666667em',
                    marginTop: '0',
                    marginBottom: '0.875em',
                    lineHeight: '1',
                },
                h2: {
                    fontSize: '2em',
                    marginTop: '1.5em',
                    marginBottom: '0.8333333em',
                    lineHeight: '1.0833333',
                },
                h3: {
                    fontSize: '1.5em',
                    marginTop: '1.5555556em',
                    marginBottom: '0.6666667em',
                    lineHeight: '1.2222222',
                },
                h4: {
                    fontSize: '1.25em',
                    marginTop: '1.6em',
                    marginBottom: '0.6em',
                    lineHeight: '1.5',
                },
                h5: {
                    fontSize: '1.125em',
                    marginTop: '1.7777778em',
                    marginBottom: '0.4444444em',
                    lineHeight: '1.5555556',
                },
                h6: {
                    fontSize: '1.125em',
                    marginTop: '1.7777778em',
                    marginBottom: '0.4444444em',
                    lineHeight: '1.5555556',
                },
                code: { fontSize: '0.9166667em' },
                pre: {
                    fontSize: '0.8333333em',
                    lineHeight: '1.8',
                    marginTop: '2em',
                    marginBottom: '2em',
                    borderRadius: '0.5rem',
                    padding: '1.2em 1.6em',
                },
            },

            // Color variants
            invert: {
                color: 'rgb(71 85 105)',
                a: { color: '#0891b2' },
                strong: { color: 'rgb(15 23 42)' },
                code: { color: 'rgb(15 23 42)', backgroundColor: 'rgb(241 245 249)' },
                pre: { color: 'rgb(15 23 42)', backgroundColor: 'rgb(241 245 249)' },
                'pre code': { color: 'inherit' },
                blockquote: { borderColor: 'rgb(203 213 225)', color: 'rgb(71 85 105)' },
                'thead th': { color: 'rgb(15 23 42)' },
                'tbody tr': { borderBottomColor: 'rgb(226 232 240)' },
                hr: { borderColor: 'rgb(226 232 240)' },
                h1: { color: 'rgb(15 23 42)' },
                h2: { color: 'rgb(15 23 42)' },
                h3: { color: 'rgb(15 23 42)' },
                h4: { color: 'rgb(15 23 42)' },
                h5: { color: 'rgb(15 23 42)' },
                h6: { color: 'rgb(15 23 42)' },
                figcaption: { color: 'rgb(71 85 105)' },
                lead: { color: 'rgb(71 85 105)' },
            },
        },
        // Другие компоненты будут добавлены позже
        button: {} as any,
        input: {} as any,
        textarea: {} as any,
        select: {} as any,
        checkbox: {} as any,
        radio: {} as any,
        switch: {} as any,
        card: {} as any,
        modal: {} as any,
        popover: {} as any,
        tooltip: {} as any,
        dropdown: {} as any,
        navbar: {} as any,
        sidebar: {} as any,
        breadcrumb: {} as any,
        table: {} as any,
        alert: {} as any,
        toast: {} as any,
        progress: {} as any,
        spinner: {} as any,
        badge: {} as any,
        avatar: {} as any,
        tabs: {} as any,
        pagination: {} as any,
    },
} satisfies BrandDescription
