export const __LINKS_COUNT = Symbol('LinksCount')
export const __DESTROY = Symbol('Destroy')
export const __IS_DESTROYED = Symbol('IsDestroyed')
export const __LINKS = Symbol('Links')
export const __EFFECTS = Symbol('Effects')
export const __EVENTS = Symbol('Events')
export const __CONTEXTS = Symbol('Contexts')
export const __CONTEXTS_EFFECTS = Symbol('ContextsLinks')
