/**
 * Generate JavaScript tokens file from Brand configuration
 * Exports design tokens for runtime use in Canvas, Three.js, etc.
 */

import type { Brand } from '@sky-modules/system/types/Brand'

export interface TokensJsConfig {
    includeComments: boolean
    format: 'esm' | 'cjs'
}

const defaultConfig: TokensJsConfig = {
    includeComments: true,
    format: 'esm',
}

/**
 * Generate tokens.js file from Brand configuration
 */
export default function generateTokensJs(
    brand: Brand,
    config: Partial<TokensJsConfig> = {}
): string {
    const cfg = { ...defaultConfig, ...config }
    let content = ''

    // Add header comment
    if (cfg.includeComments) {
        content += `/**\n`
        content += ` * Design Tokens\n`
        content += ` * Auto-generated from brand configuration\n`
        content += ` * Do not edit this file directly\n`
        content += ` */\n\n`
    }

    // Build tokens object
    const tokens: Record<string, any> = {}

    // Foundation tokens
    if (brand.foundation) {
        if (brand.foundation.colors) {
            tokens.colors = brand.foundation.colors
        }
        if (brand.foundation.typography) {
            tokens.typography = brand.foundation.typography
        }
        if (brand.foundation.spacing) {
            tokens.spacing = brand.foundation.spacing
        }
        if (brand.foundation.sizing) {
            tokens.sizing = brand.foundation.sizing
        }
        if (brand.foundation.radius) {
            tokens.radius = brand.foundation.radius
        }
        if (brand.foundation.elevation) {
            tokens.elevation = brand.foundation.elevation
        }
        if (brand.foundation.animation) {
            tokens.animation = brand.foundation.animation
        }
        if (brand.foundation.breakpoints) {
            tokens.breakpoints = brand.foundation.breakpoints
        }
    }

    // Semantic tokens
    if (brand.semantic) {
        tokens.semantic = brand.semantic
    }

    // Layout tokens
    if (brand.layout) {
        tokens.layout = brand.layout
    }

    // Convert to JSON string
    const tokensStr = JSON.stringify(tokens, null, cfg.includeComments ? 2 : 0)

    // Generate export based on format
    if (cfg.format === 'esm') {
        content += `export const tokens = ${tokensStr};\n\n`
        content += `export default tokens;\n`
    } else {
        // CommonJS
        content += `const tokens = ${tokensStr};\n\n`
        content += `module.exports = tokens;\n`
        content += `module.exports.tokens = tokens;\n`
    }

    return content
}
